# Generated by Django 2.2.5 on 2019-10-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20191001_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
