# Generated by Django 2.2.6 on 2019-10-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_auto_20191001_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
