# Generated by Django 2.2.6 on 2019-10-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_house_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='house',
            name='slug',
        ),
    ]
