# Generated by Django 2.2.6 on 2019-10-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedhouses',
            name='booked_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to='accounts.Profile'),
        ),
    ]
