# Generated by Django 2.2.6 on 2019-10-07 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20191005_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedhouses',
            name='booked_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booked', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='bookedhouses',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booked_house', to='houses.House'),
        ),
    ]
